# Generated by Django 4.1.1 on 2022-09-25 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carmodel_brand_alter_carmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
