# Generated by Django 4.1.1 on 2022-09-25 16:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
